# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('tcp-scada-application-example', ['tcp-scada-application'])
    obj.source = 'tcp-scada-application-example.cc'

